### ISSUE TITLE
Incompatibility with new regular expression syntax in older Safari versions causes blank page

### ISSUE THREAD

**Issue by myfjdthink** [syntax-tree/mdast-util-gfm-autolink-literal#11] opened 2024-08-29 09:26 UTC
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

2.0.1

### Steps to reproduce

Use the mdast-util-gfm-autolink-literal package in your project.

Run the project in an older version of the Safari(<16.3) browser.

like: https://github.com/nuxt/nuxt/issues/26393

### Expected behavior

The regular expression should work correctly, allowing the page to render without issues.

### Actual behavior

In older versions of the Safari browser, the regular expression is not supported, leading to a blank page (white screen).

### Affected runtime and version

node@18.2

### Affected package manager and version

yarn

### Affected OS and version

Safari 15.7

**Comment by myfjdthink** [comment] 2024-08-29 09:31
![image](https://github.com/user-attachments/assets/379d876e-bff7-4f95-9599-f82e24919519)
test in safari console

**Comment by myfjdthink** [comment] 2024-08-29 09:31
https://github.com/syntax-tree/mdast-util-gfm-autolink-literal/blame/182000e93a49c259d362e6d3f474b13d35b6472d/lib/index.js#L135

**Comment by wooorm** [comment] 2024-08-29 12:02
Duplicate of #10

**Closed as not planned by wooorm** 2024-08-29 12:02 UTC
Labels: 👯 no/duplicate, 👎 phase/no
