### ISSUE TITLE
Regex not compatible on lower versions of IOS / Safari

### ISSUE THREAD

**Issue by laomu1024** [syntax-tree/mdast-util-gfm-autolink-literal#12] opened 2024-12-10 03:03 UTC
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=issues) and [discussions](https://github.com/orgs/syntax-tree/discussions) and couldn’t find anything (or linked relevant results below)

### Affected package

remark-gfm4.0.0

### Steps to reproduce

[/(?<=^|\s|\p{P}|\p{S})([-.\w+]+)@([-\w]+(?:\.[-\w]+)+)/gu, findEmail]

Create JS crash on Safari / IOS(15.3)

### Actual behavior

got error "Invalid regular expression: invalid group specifier name"

### Expected behavior

not got error

**Comment by ChristianMurphy** [comment] 2024-12-10 03:18
Duplicate of https://github.com/syntax-tree/mdast-util-gfm-autolink-literal/issues/10

**Closed as not planned by ChristianMurphy** 2024-12-10 03:18 UTC
Labels: 👯 no/duplicate, 🤞 phase/open
